config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_up/:account_patarn' => 'users/registrations#new', as: :new_user_registration_customize
    get '/users/edit/:account_patarn' => 'users/registrations#edit', as: :edit_user_registration_customize
    get '/users/complete/:sign_in_count' => 'users/registrations#complete', as: :new_user_registration_complete
    get '/users/send/:sign_in_count' => 'users/registrations#mail_send', as: :new_user_registration_send
    get '/users/delete' => 'users/registrations#delete', as: :delete_user
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :top, only: :index
  resources :users, only: [:index]
  get 'users/my_page/:info_patarn' => "users#my_page", as: :user_my_page
  resources :video, only: :show do
    collection do
      # get 'genre_search'
      get 'chef_search'
      get 'search'
      get 'make_suggest'
    end
  end

  get 'video/chef_search_video/:chef_id' => "video#chef_search_video"
  resources :article, only: [:index, :show] do
    collection do
      get 'genre_search'
      get 'search'
    end
  end

  resources :payments, only: [:edit, :create, :destroy] do
    collection do
      post 'purchase_charge'
      post 'purchase_subscription'
      post 'card_change'
    end
  end
  get 'payments/new_card/:pay_patarn' => "payments#new_card", as: :new_card_registration
  get 'payments/delete' => "payments#delete", as: :delete_payment

  post   '/video_like/:video_id' => 'video_likes#create', as: 'video_like_create'
  delete '/video_like/:video_id' => 'video_likes#destroy', as: 'video_like_destroy'
  post   '/article_like/:article_id' => 'article_likes#create', as: 'article_like_create'
  delete '/article_like/:article_id' => 'article_likes#destroy', as: 'article_like_destroy'

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
    end
  end

  resources :magazine, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      post 'confirm'
    end
  end

  root 'top#index'

  get '/sitemap' => 'sitemaps#index' 
end

app/views/share/_article_list.html.haml
- articles.each do |article|
	.a-search-result__box.no-bottom-border
		= link_to article_path(article.id) do
			.a-search-result__box__image
				= image_tag article.thumbnail.url , alt: "article"
			.a-search-result__box__detail
				.a-search-result__box__detail__title
					= article.title
				.a-search-result__box__detail__text
					- if article.description
						= article.description
					- else
						!= article.contents

app/views/share/_footer.html.haml
.footer
  .footer__top
    .footer__top__col
      .footer__top__col__box
        %ul
          %li
            = link_to "https://restaurant-education.co.jp/cook-lab/" do
              COOK LAB.について
          %li
            = link_to "https://restaurant-education.co.jp/", {:target => "_blank"} do
              運営会社
          %li
            = link_to page_path('tos') do
              利用規約
          %li
            = link_to page_path('privacy') do
              プライバシーポリシー
          %li
            = link_to page_path('commerce') do
              特定商取引法に基づく表示
    .footer__top__col
      .footer__top__col__box
        %ul
          %li
            = link_to page_path('qa') do
              よくあるご質問
          %li
            = link_to new_contact_path do
              お問い合わせ
          - if user_signed_in? && check_pay_regi_status != 2
            %li
              = link_to delete_user_path do
                退会手続き
  .footer__sns
    .footer__sns__btn.tw
      = link_to "https://twitter.com/COOKLAB2", target: "_blank" do
        = fa_icon "twitter"
    .footer__sns__btn.fb
      = fa_icon "facebook"
    .footer__sns__btn.insta
      = link_to "https://www.instagram.com/cooklabgram/?hl=ja", target: "_blank" do
        = fa_icon "instagram", class: "insta-logo"
  .footer__bottom
    %p
      = "@Copyright 2018 Restaurant Education, Inc. All Rights Reserved."

app/views/share/_genre-select.html.haml
.select
  .select__window
    = form_tag(@genre_search_path, method: :get, id: "select-form" ) do
      = select_tag :search_genre_name, options_for_select(@genre_tags), class: "select-btn", prompt: "ジャンルを選択してください"

app/views/share/_header.html.haml
.header
  .header__logo
    = link_to root_path do
      = image_tag "cook_lab2.png", size: "210x45", alt: "cooklab"
  %nav.header__menu
    %ul.header__menu__list
      - if user_signed_in?
        %li
          = link_to user_my_page_path('notice') do
            = "マイページ"
        %li
          = link_to destroy_user_session_path, method: :delete do
            = "ログアウト"
      - else
        %li
          = link_to users_path do
            %span.new-btn
              = "メルマガ会員登録"
        %li
          = link_to new_user_session_path do
            = "ログイン"
      / %li.search-nav-sp
      /   %label{ for: "menu_bar01" }
      /     %span.sp-only
      /       = fa_icon "play-circle"
      /     = "動画検索"
      /   %input{ type: "checkbox", id: "menu_bar01", class: "accordion" }
      /   %ul{ id: "links01"}
      /     %li
      /       = link_to search_video_index_path do
      /         = fa_icon "search"
      /         = "キーワード検索"
      /     - unless controller_name == 'top'
      /       %li
      /         = render 'share/search-window-header-sp'
      /     %li
      /       = link_to genre_search_video_index_path do
      /         = image_tag "genre_icon.png", size: "40x40"
      /         = "ジャンル検索"
      /     %li
      /       = link_to chef_search_video_index_path do
      /         = image_tag "chef_icon.png", size: "40x40"
      /         = "料理人検索"
      / %li.search-nav-sp
      /   %label{ for: "menu_bar02" }
      /     %span.sp-only
      /       = fa_icon "book"
      /     = "記事検索"
      /   %input{ type: "checkbox", id: "menu_bar02", class: "accordion" }
      /   %ul{ id: "links02"}
      /     %li
      /       = link_to article_index_path do
      /         = fa_icon "book"
      /         = "記事一覧"
      /     %li
      /       = link_to genre_search_article_index_path do
      /         = image_tag "genre_icon.png", size: "40x40"
      /         = "ジャンル検索"
      /     %li
      /       = link_to search_article_index_path do
      /         = fa_icon "search"
      /         = "キーワード検索"
      / - if user_signed_in?
      /   %li.search-nav-sp
      /     %label{ for: "menu_bar03" }
      /       %span.sp-only
      /         = fa_icon "user"
      /       = "マイページ"
      /     %input{ type: "checkbox", id: "menu_bar03", class: "accordion" }
      /     %ul{ id: "links03"}
      /       %li
      /         = link_to user_my_page_path('notice') do
      /           = fa_icon "bell"
      /           = "お知らせ"
      /           - if @unread_notices > 0
      /             %span.unread-alart
      /               = fa_icon "exclamation-circle"
      /       %li
      /         = link_to user_my_page_path('profile') do
      /           = fa_icon "address-card"
      /           = "プロフィール"
      /       %li
      /         = link_to user_my_page_path('pay_video') do
      /           = fa_icon "shopping-cart"
      /           = "購入した動画"
      /       %li
      /         = link_to user_my_page_path('like_video') do
      /           = fa_icon "heart"
      /           = "お気に入り(動画)"
      /       %li
      /         = link_to user_my_page_path('like_article') do
      /           = fa_icon "heart"
      /           = "お気に入り(記事)"
      /       %li
      /         = link_to user_my_page_path('pay_info') do
      /           = fa_icon "credit-card"
      /           = "支払情報"
  .header__search-icon
    = fa_icon "search"
  .header__search-close-icon
    = fa_icon "times"

app/views/share/_like-btn.html.haml
- if user_signed_in? && (controller.controller_name == 'article' || controller.controller_name == 'article_likes')
  - if like.like_user(current_user.id)
    .share-frame__like-count.like-off
      = link_to article_like_destroy_path(like.id), method: :delete, remote: true do
        .text
          = fa_icon "heart"
          = like.like_count
        .fukidashi
          お気に入りを解除する
  - else
    .share-frame__like-count
      - if (current_user_like_count < 15 && check_pay_regi_status != 2) || (current_user_like_count < 100 && check_pay_regi_status == 2)
        = link_to article_like_create_path(like.id), method: :post, remote: true do
          .text
            = fa_icon "heart"
            = like.like_count
          .fukidashi
            お気に入りに登録する
      - else
        = link_to "#", id: "like_count_btn" do
          .text
            = fa_icon "heart"
            = like.like_count
          .fukidashi
            お気に入りに登録する
- elsif user_signed_in? && (like.price == 0 || video_charge_check(like) == 1 || check_pay_regi_status == 2)
  - if like.like_user(current_user.id)
    .share-frame__like-count.like-off
      = link_to video_like_destroy_path(like.id), method: :delete, remote: true do
        .text
          = fa_icon "heart"
          = like.like_count
        .fukidashi
          お気に入りを解除する
  - else
    .share-frame__like-count
      - if (current_user_like_count < 15 && check_pay_regi_status != 2) || (current_user_like_count < 100 && check_pay_regi_status == 2)
        = link_to video_like_create_path(like.id), method: :post, remote: true do
          .text
            = fa_icon "heart"
            = like.like_count
          .fukidashi
            お気に入りに登録する
      - else
        = link_to "#", id: "like_count_btn" do
          .text
            = fa_icon "heart"
            = like.like_count
          .fukidashi
            お気に入りに登録する
- else
  .share-frame__like-count.like-off
    .text
      = fa_icon "heart"
      = like.like_count

app/views/share/_like-share.html.haml
.share-frame
  .share-frame__like-btn
    - if controller.controller_name == 'video'
      = render "share/like-btn", like: @video, current_user_like_count: @current_user_like_count
    - else
      = render "share/like-btn", like: @article, current_user_like_count: @current_user_like_count
.share-frame
  = link_to "http://twitter.com/share?url=#{request.url}", class: "share-frame__btn tw" do
    = fa_icon "twitter"
    = "ツイート"
.share-frame
  = link_to "https://www.facebook.com/sharer/sharer.php?u=#{request.url}", class: "share-frame__btn fb" do
    = fa_icon "facebook"
    = "シェア"

app/views/share/_magazine_intro.html.haml
.magazine-intro
  .magazine-intro__title
    = image_tag "cooklab_magazine_logo.jpg", alt: "cooklab_magazine_logo"
    %br
    創刊しました！
  .magazine-intro__content
    .magazine-intro__content__image
      = image_tag "cooklab_magazine_intro.png", alt: "cooklab_magazine"
    .magazine-intro__content__description
      .title
        「役立つ気付き」と「旬な情報」を無料で届ける
      .text
        これまで、飲食店の経営者や働く人たちが、学習のために購入していた料理専門誌や雑誌を、ゼロ円で届けるというのが本誌の大きな特徴です。記事や掲載するレシピの多くは本サイトでも紹介しておりますが、雑誌形式で手に取りやすく、読みやすいものになっています。指定場所への送付は会員様だけの特別サービスです。限定記事もございますので、毎号、楽しみにお待ち下さい。(隔月発行)
  .magazine-intro__btn
    - if not user_signed_in?
      = link_to users_path do
        %span.pc-only
          = "メルマガ会員募集中！無料特典あり♪"
        %span.sp-only
          = "メルマガ会員募集中！"
          %br
          = "無料特典あり♪"
    - else
      - if @magazine_address_check
        = link_to new_card_registration_path(pay_patarn: 'subscription'), class: "premium" do
          %span.pc-only
            = "月額300円(税別)のメルマガ有料会員に登録して、定期購読しよう！"
          %span.sp-only
            = "月額300円(税別)の"
            %br
            = "メルマガ有料会員に登録して"
            %br
            = "定期購読しよう！"
      - else
        = link_to new_magazine_path, class: "premium" do
          %span.pc-only
            = "月額300円(税別)のメルマガ有料会員に登録して、定期購読しよう！"
          %span.sp-only
            = "月額300円(税別)の"
            %br
            = "メルマガ有料会員に登録して"
            %br
            = "定期購読しよう！"

app/views/share/_navigation-bar.html.haml
.footer-navi
  - if user_signed_in?
    %ul
      %li
        = link_to root_path do
          .icon
            = fa_icon "home"
          .text
            ホーム
      %li.search-btn
        .icon
          = fa_icon "search"
        .text
          さがす
      %li
        = link_to destroy_user_session_path, method: :delete do
          .icon
            = fa_icon "sign-out"
          .text
            ログアウト
      %li
        = link_to user_my_page_path('notice') do
          .icon
            = fa_icon "user"
          .text
            マイページ
  - else
    %ul
      %li
        = link_to root_path do
          .icon
            = fa_icon "home"
          .text
            ホーム
      %li.search-btn
        .icon
          = fa_icon "search"
        .text
          さがす
      %li
        = link_to users_path, class: "navigation-bar-sign-up-link" do
          .icon
            = fa_icon "user"
          .text
            会員登録
      %li
        = link_to new_user_session_path, class: "navi-login-btn" do
          .icon
            = fa_icon "sign-in"
          .text
            ログイン
      %li
        .icon
        .text

app/views/share/_search-header.html.haml
.search__header.light-gray
  - if @search_patarn == 'chef-video'
    .search__header__word.font-bold
      = "「#{@chef.name}」さん"
      %span.font-normal
        = "の動画"
        .total-hit-count
          = result.total_count
  - elsif controller.controller_name == 'article'
    .search__header__word
      - if @search_word.present? || @genre_name.present?
        - if @search_word.present?
          = "検索キーワード："
          %span.font-bold
            = "「#{@search_word}」"
        - if @genre_name.present?
          = "ジャンル："
          %span.font-bold
            = "「#{@genre_name.map { |c| c }.join(',')}」"
        = "に関する記事"
      - else
        = "すべての記事一覧"
      .total-hit-count
        = result.total_count
  - elsif @search_patarn == 'chef_genre' && @search_word.present?
    .search__header__word
      %span.font-bold
        = "「#{@search_word}」"
      = "専門の料理人一覧"
      .total-hit-count
        = result.total_count
  - elsif controller.action_name == 'chef_search'
    .search__header__word
      - if @search_word.nil?
        すべての料理人
      - else
        = "検索キーワード："
        %span.font-bold
          = "「#{@search_word}」"
      .total-hit-count
        = result.total_count
  - elsif controller.controller_name == 'video'
    .search__header__word
      - if @search_word.present?
        = "検索キーワード："
        %span.font-bold
          = "「#{@search_word}」"
      - if @series_title.present?
        = "シリーズ："
        %span.font-bold
          = "「#{@series_title.map { |s| s }.join(',')}」"
      - if @genre_name.present?
        = "ジャンル："
        %span.font-bold
          = "「#{@genre_name.map { |c| c }.join(',')}」"
      - if @chef_name.present?
        = "料理人："
        %span.font-bold
          = "「#{@chef_name}」"
      - if (@chef_name.nil? || @chef_name == "") && (@search_word.nil? || @search_word == "") && (@genre_name.nil? || @genre_name == "") && (@series_title.nil? || @series_title == "")
        = "すべての動画一覧"
      .total-hit-count
        = result.total_count
  - elsif controller.controller_name == 'article' && action_name == 'index' && result.present?
    .search__header__word
      = "すべての記事"
      .total-hit-count
        - if params[:order] == 'new' || params[:order].nil?
          = all_article_count_for_index_page(result.total_count)
        - else
          = result.total_count
  - if @search_patarn != 'chef_genre' && controller.action_name != 'chef_search' && (@search_patarn == 'chef-video' || @search_word.present? || result.present?)
    .search__header__order
      = form_tag(request.url, method: :get, id: "order-select") do
        = select_tag :order_patarn, options_for_select(show_order_select_list, selected: params[:order_patarn]), class: "order-select-btn"
        - if controller.controller_name == 'video'
          = hidden_field_tag :search_word, @search_word
          - if @chef_name.present?
            - @chef_name.split(",").each do |c|
              = hidden_field_tag "search_chef_name[]", c
          - else
            = hidden_field_tag "search_chef_name[]", nil
          - if @chef_id.present?
            - @chef_id.each do |c|
              = hidden_field_tag "search_chef_id[]", c
          - else
            = hidden_field_tag "search_chef_id[]", nil
          - if @genre_name.present?
            - @genre_name.each do |g|
              = hidden_field_tag "search_genre_name[]", g
          - else
            = hidden_field_tag "search_genre_name[]", nil
          - if @series_id.present?
            - @series_id.each do |s|
              = hidden_field_tag "search_series_id[]", s
            - if @series_title.present?
              - @series_title.each do |s|
                = hidden_field_tag "search_series_title[]", s
          - else
            = hidden_field_tag "search_series_id[]", nil
        - elsif controller.controller_name == 'video' && params[:suggest_patarn] == 'series'
          = hidden_field_tag :suggest_patarn, 'series'
          = hidden_field_tag :search_word, @search_word
        - elsif @search_patarn == 'genre'
          = hidden_field_tag :search_genre_name, @genre_name
        - elsif controller.controller_name == 'article'
          = hidden_field_tag :search_word, @search_word
          = hidden_field_tag :search_genre_name, @genre_name

app/views/share/_search-window-header.html.haml
.search-window
  .search-window__input
    = text_field_tag :search_word, nil, class: "s-window", autocomplete: 'off'
    = hidden_field_tag :suggest_patarn, nil, id: "suggest_patarn_sp"
    = hidden_field_tag :search_patarn, @search_patarn
  .search-window__icon
    = button_tag type: "submit", class: "s-submit" do
      = fa_icon "search"

app/views/share/_search-window.html.haml
.search-window.sp-search-window
  = form_tag(@search_path, method: :get) do
    .search-window__input
      = text_field_tag :search_word, nil, placeholder: "キーワードを入力", class: "s-window", id: "search-field", autocomplete: 'off'
      = hidden_field_tag :order_patarn, 'new'
    .search-window__icon
      = button_tag type: "submit", class: "s-submit" do
        = fa_icon "search"

app/views/share/_search_frame.html.haml
.search-frame
	.search-frame__title
		%span
			= fa_icon "search", class: "icon"
			動画をさがす
	= form_tag('/video/search', method: :get, class: "video-search-form") do
		.search-frame__box
			.search-frame__box__title
				キーワード
			.search-frame__box__content
				= render 'share/search-window-header'
		.search-frame__box
			.search-frame__box__title
				ジャンル
			.search-frame__box__content
				- @video_all_genres.each do |g|
					.genre-tag
						= g.name
						= check_box_tag "search_genre_name[]", g.name, nil, class: "search_check_box"
		.search-frame__box
			.search-frame__box__title
				シリーズ
			.search-frame__box__content
				- Series.all.each do |s|
					.series-tag
						= s.title
						= check_box_tag "search_series_id[]", s.id, nil, class: "search_check_box"
						= check_box_tag "search_series_title[]", s.title, nil, class: "search_check_box"
		.search-frame__box
			.search-frame__box__title
				料理人
			.search-frame__box__content
				- @all_chefs.each do |c|
					.topic-tag
						= c.name
						= check_box_tag "search_chef_id[]", c.id, nil, class: "search_check_box"
						= check_box_tag "search_chef_name[]", c.name, nil, class: "search_check_box"
			.search-frame__box__sub-info
				= link_to chef_search_video_index_path do
					料理人について詳しく見る>>
		.search-frame__submit
			= hidden_field_tag :order_patarn, 'new'
			.search-frame__submit__btn.video-search-submit
				動画をさがす
	.search-frame__title
		%span
			= fa_icon "search", class: "icon"
			記事をさがす
	= form_tag('/article/search', method: :get, class: "article-search-form") do
		.search-frame__box
			.search-frame__box__title
				キーワード
			.search-frame__box__content
				= render 'share/search-window-header'
		.search-frame__box
			.search-frame__box__title
				ジャンル
			.search-frame__box__content
				- @article_all_genres.each do |g|
					.genre-tag
						= g.name
						= check_box_tag "search_genre_id[]", g.id, nil, class: "search_check_box"
						= check_box_tag "search_genre_name[]", g.name, nil, class: "search_check_box"
		.search-frame__submit
			= hidden_field_tag :order_patarn, 'new'
			.search-frame__submit__btn.article-search-submit
				記事をさがす

app/views/share/_tag-list.html.haml
.tag-list
  %p
    = fa_icon "tag"
    %u
      おすすめのジャンル
  - tags.each do |tag|
    = link_to genre_search_video_index_path(genre: tag.name) do
      .tag-list__box
        = "#{ tag.name } (#{ Video.tag_count(tag) })"

app/views/share/_video_list.html.haml
.v-list
  - videos.each do |video|
    .v-list__box
      = link_to video_path(video.id) do
        .v-list__box__thumbnail
          = image_tag video.thumbnail.url , alt: "video"
          - if new_video_check(video.created_at)
            .new-icon
              = image_tag "new.png",size: "50x50", alt: "new"
          .like-and-chef
            .date
              %p
                = fa_icon "heart"
                = video.like_count
            .chef
              %p
                = image_tag "chef_icon.png", alt: "chef"
                = video.series.chef.name
        .v-list__box__detail
          .v-list__box__detail__title
            %p
              = video.title