config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_up/:account_patarn' => 'users/registrations#new', as: :new_user_registration_customize
    get '/users/edit/:account_patarn' => 'users/registrations#edit', as: :edit_user_registration_customize
    get '/users/complete/:sign_in_count' => 'users/registrations#complete', as: :new_user_registration_complete
    get '/users/send/:sign_in_count' => 'users/registrations#mail_send', as: :new_user_registration_send
    get '/users/delete' => 'users/registrations#delete', as: :delete_user
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :top, only: :index
  resources :users, only: [:index]
  get 'users/my_page/:info_patarn' => "users#my_page", as: :user_my_page
  resources :video, only: :show do
    collection do
      # get 'genre_search'
      get 'chef_search'
      get 'search'
      get 'make_suggest'
    end
  end

  get 'video/chef_search_video/:chef_id' => "video#chef_search_video"
  resources :article, only: [:index, :show] do
    collection do
      get 'genre_search'
      get 'search'
    end
  end

  resources :payments, only: [:edit, :create, :destroy] do
    collection do
      post 'purchase_charge'
      post 'purchase_subscription'
      post 'card_change'
    end
  end
  get 'payments/new_card/:pay_patarn' => "payments#new_card", as: :new_card_registration
  get 'payments/delete' => "payments#delete", as: :delete_payment

  post   '/video_like/:video_id' => 'video_likes#create', as: 'video_like_create'
  delete '/video_like/:video_id' => 'video_likes#destroy', as: 'video_like_destroy'
  post   '/article_like/:article_id' => 'article_likes#create', as: 'article_like_create'
  delete '/article_like/:article_id' => 'article_likes#destroy', as: 'article_like_destroy'

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
    end
  end

  resources :magazine, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      post 'confirm'
    end
  end

  root 'top#index'

  get '/sitemap' => 'sitemaps#index' 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :confirmable, :lockable
  has_one :userProfile, dependent: :destroy, inverse_of: :user
  has_one :payment, dependent: :destroy, inverse_of: :user
  has_one :magazine_address, dependent: :destroy, inverse_of: :user
  has_many :charges, dependent: :destroy
  has_many :cardRegistrationRestrict, dependent: :destroy
  has_many :videos, through: :charges
  has_many :notices, through: :noticeUsers
  has_many :noticeUsers, dependent: :destroy
  has_many :video_likes, dependent: :destroy
  has_many :article_likes, dependent: :destroy
  accepts_nested_attributes_for :userProfile
  validates :name, presence: true, length: { in: 1..15 }

  enum pay_regi_status: { "無料会員" => 0, "カード登録のみ" => 1, "メルマガ有料会員" => 2 }

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    User.find_by(provider: auth.provider, uid: auth.uid)
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    User.find_by(provider: auth.provider, uid: auth.uid)
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.provider = data["provider"] if user.provider.blank?
        user.uid = data["uid"] if user.uid.blank?
        user.password = Devise.friendly_token[0, 20] if user.password.blank?
      end
      if data = session["devise.twitter_data"]
        user.email = data["email"] if user.email.blank?
        user.provider = data["provider"] if user.provider.blank?
        user.uid = data["uid"] if user.uid.blank?
        user.password = Devise.friendly_token[0, 20] if user.password.blank?
      end
    end
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update(params, *options)
    clean_up_passwords
    result
  end

  def self.update_pay_regi_status(user, pay_patarn)
    user.pay_regi_status = 1 if pay_patarn == 'charge' # 1 = カード登録済み(定額課金ではない),2 = 定額課金利用
    user.pay_regi_status = 2 if pay_patarn == 'subscription'
    user.save!
  end

  def self.delete_user_subscription_data(user)
    user.pay_regi_status = 1
    user.save!
    user.payment.subscription_id = nil
    user.payment.plan_id = nil
    user.payment.save!
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?
    if resource.errors.empty?
      set_flash_message(:notice, :confirmed) if is_flashing_format?
      sign_in_count = sign_in_count_check
      sign_in(resource)
      mail_regi_to_payjp(resource) unless resource.pay_regi_status.to_i.zero?
      respond_with_navigational(resource) { redirect_to after_confirmation_path_for(resource_name, resource, sign_in_count) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity) { render :new }
    end
  end

  protected

  def after_confirmation_path_for(resource_name, resource, sign_in_count)
    new_user_registration_complete_path(sign_in_count)
  end

  def sign_in_count_check
    sign_in_count = if user_signed_in?
                      current_user.sign_in_count
                    else
                      0
                    end
  end

  def mail_regi_to_payjp(resource)
    Payjp.api_key = Settings.payjp[:PAYJP_SECRET_KEY]
    customer_id = resource.payment.customer_id
    customer = Payjp::Customer.retrieve(id: customer_id)
    customer.email = resource.email
    customer.save
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])
    if @user
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      @user = User.new
      redirect_to new_user_registration_customize_path('facebook')
    end
  rescue => e
    set_flash_message(:alert, :failure, kind: "Facebook") if is_navigational_format?
    failure
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    if @user
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      @user = User.new
      redirect_to new_user_registration_customize_path('twitter')
    end
  rescue => e
    set_flash_message(:alert, :failure, kind: "Twitter") if is_navigational_format?
    failure
  end

  protected

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up/:account_patarn
  def new
    @account_patarn = account_patarn_params[:account_patarn]
    super
  end

  # POST /resource
  def create
    @account_patarn = account_patarn_params[:account_patarn]
    @user = User.new(configure_sign_up_params) if @account_patarn == 'mail'
    @user = User.new(configure_sign_up_params_fb) if @account_patarn == 'facebook'
    @user = User.new(configure_sign_up_params_tw) if @account_patarn == 'twitter'
    @user.skip_confirmation! unless @account_patarn == 'mail'
    if @user.save
      switch_redirect_to(@account_patarn, @user)
    else
      render 'new'
    end
  end

  # GET /resource/edit
  def edit
    @account_patarn = current_user.provider
    @account_patarn = 'mail' if current_user.provider.nil?
    @user = current_user
    super
  end

  # PUT /resource
  def update
    @account_patarn = account_patarn_params[:account_patarn]
    if @user.update_without_current_password(configure_account_update_params)
      # sign_in(@user, bypass: true)
      bypass_sign_in(@user)
      switch_mail_aouth_redirect_to(@account_patarn, @user)
    else
      render 'edit'
    end
  end

  # GET /resource/cancel
  def delete
  end

  # DELETE /resource
  def destroy
    delete_payment_data(current_user) if current_user.payment.present?
    MagazineAddress.delete_address(current_user) if MagazineAddress.find_by(user_id: current_user.id)
    current_user.destroy
    sign_out
    @sign_in_count = 'delete'
    render 'complete'
  end

  def mail_send
    @sign_in_count = configure_mail_aouth_params[:sign_in_count].to_i
  end

  def complete
    @sign_in_count = configure_mail_aouth_params[:sign_in_count].to_i
    @magazine_address_check = MagazineAddress.register_check(current_user)
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up) do |params|
      params.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :pay_regi_status, userProfile_attributes: [:sex, :work_place, :job, :specialized_field, :location, :birthday]])
    end
  end

  def configure_sign_up_params_fb
    configure_sign_up_params.merge(provider: session["devise.facebook_data"]['provider'], uid: session["devise.facebook_data"]['uid'], email: session["devise.facebook_data"]['info']['email'], password: Devise.friendly_token[0, 20])
  end

  def configure_sign_up_params_tw
    configure_sign_up_params.merge(provider: session["devise.twitter_data"]['provider'], uid: session["devise.twitter_data"]['uid'], email: session["devise.twitter_data"]['info']['email'], password: Devise.friendly_token[0, 20])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.sanitize(:account_update) do |params|
      params.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :pay_regi_status, userProfile_attributes: [:sex, :work_place, :job, :specialized_field, :location, :birthday]])
    end
  end

  def account_patarn_params
    if action_name == 'new'
      params.permit(:account_patarn)
    else
      params.require(:user).permit(:account_patarn)
    end
  end

  def configure_mail_aouth_params
    params.permit(:sign_in_count)
  end

  def switch_redirect_to(account_patarn, resource)
    if account_patarn == 'mail'
      redirect_to new_user_registration_send_path(@user.sign_in_count)
    else
      sign_in(resource)
      redirect_to new_user_registration_complete_path(0)
    end
  end

  def switch_mail_aouth_redirect_to(account_patarn, resource)
    if resource.unconfirmed_email.nil?
      @sign_in_count = 'edit'
      render 'complete'
    else
      redirect_to new_user_registration_send_path(resource.sign_in_count)
    end
  end

  def delete_payment_data(current_user)
    #MyPayjp.delete_customer(current_user.payment.customer_id)
    current_user.payment.destroy
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def my_page
    account_patarn_check
    @info_patarn = configure_info_patarn_params[:info_patarn]
    @notices = Notice.all.order("id desc").limit(3) if @info_patarn == 'notice'
    old_read_notice_delete(@new_notice_ids) && unread_notice_to_read if @info_patarn == 'notice' && @unread_notice_ids.present?
    @videos = current_user.videos.page(params[:page]).per(10) if @info_patarn == 'pay_video'
    @videos = make_like_video_list if @info_patarn == 'like_video'
    @articles = make_like_article_list if @info_patarn == 'like_article'
    @magazine_address_check = MagazineAddress.register_check(current_user)
    @addressee = make_addressee_text if @magazine_address_check 
    return unless @info_patarn == 'pay_info' && current_user.payment.present?
    get_card_info(current_user)
  end

  private

  def account_patarn_check
    @account_patarn = current_user.provider
    @account_patarn = 'mail' if current_user.provider.nil?
    @account_aouth = 'Facebook' if @account_patarn == 'facebook'
    @account_aouth = 'twitter' if @account_patarn == 'twitter'
    @account_aouth = 'メールアドレス' if @account_patarn == 'mail'
  end

  def configure_info_patarn_params
    params.permit(:info_patarn)
  end

  def change_card_name(brand)
    if brand == 'American Express'
      'AmericanExpress'
    else
      'DinersClub'
    end
  end

  def get_card_info(user)
    card = MyPayjp.get_card_data(user)
    brand = card.brand
    brand = change_card_name(brand) if ['American Express', 'Diners Club'].include?(brand)
    @card_brand = brand
    @last4 = card.last4
    @exp_month = card.exp_month
    @exp_year = card.exp_year
    @expires_at = current_user.payment.expires_at
  end

  def make_like_video_list
    like_videos = VideoLike.where(user_id: current_user.id).includes(:video)
    videos = []
    like_videos.each do |like_video|
      videos << like_video.video
    end
    Kaminari.paginate_array(videos).page(params[:page]).per(10)
  end

  def make_like_article_list
    like_articles = ArticleLike.where(user_id: current_user.id).includes(:article)
    articles = []
    like_articles.each do |like_article|
      articles << like_article.article
    end
    Kaminari.paginate_array(articles).page(params[:page]).per(10)
  end

  def unread_notice_to_read
    @unread_notice_ids.each do |notice_id|
      NoticeUser.create(user_id: current_user.id, notice_id: notice_id)
    end
    @unread_notices = 0
  end

  def old_read_notice_delete(new_notices)
    NoticeUser.where.not(notice_id: new_notices).where(user_id: current_user.id).destroy_all
  end

  def make_addressee_text
    @magazine_address = MagazineAddress.find_by(user_id: current_user.id)
    addressee = (@magazine_address.pref + @magazine_address.city_address[0..4]) + '******'
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def adjust_expires_at(expires_at)
    expires_at.to_s.dup.sub!(/\s.*/, "")
  end

  def menu_active(info_patarn, page_action)
    'selected' if info_patarn == page_action
  end

  def check_pay_regi_status
    current_user.pay_regi_status_before_type_cast
  end
end

app/views/users/_account-plan.html.haml
.account-plan
  .mail-magazine-special
    %span
      COOK LAB.
    %br
    メルマガ会員だけの特典！
  %table
    %tr
      %th.none_cell
      %th
        メルマガ会員
        / %th
        /   有料会員
    %tr
      %th
        ご利用料金
      %td
        0円
        / %td
        /   %span
        /     300
        /   %span
        /     円
        /   %span
        /     (税抜き)
    %tr
      %th
        動画視聴
      %td
        見放題
        / %td
        /   見放題
    %tr
      %th
        お気に入り登録
        %span.supText
          ※1
      %td
        15件まで
        / %td
        /   %span
        /     100
        /   %span
        /     件まで
    %tr
      %th
        レシピ閲覧
      %td
        ○
        /   %td
        /     ○
        / %tr
        /   %th
        /     メルマガ配信
        /     %span.supText
        /       ※2
        /   %td
        /     ○
        / %td
        /   ○
        / %tr
        /   %th
        /     %span
        /       COOK LAB.
        /       %br
        /       Magazine
        /       %br
        /       定期購読サービス
        /     %br
        /       = image_tag "cooklab_magazine.jpg", alt: "cooklab_magazine"
        /   %td
        /     ×
        /   %td
        /     ○
        /     %span.supText
        /       ※3
  %ul.notification_list
    %li
      ※1: 動画および記事それぞれに対して有効な登録上限数となります。
      / %li
      /   ※2: 新着動画・記事情報を 月１回程度を目処に配信。
      / %li
      /   ※3: 隔月で発行。ご指定の住所に冊子をお届けするため、住所登録が必要となります。

      

app/views/users/_my-page_menu.html.haml
.my-page__menu__list-pc
  %ul
    = link_to user_my_page_path('notice') do
      %li{ class: "#{menu_active(@info_patarn, 'notice')}" }
        %p.left
          お知らせ
          - if @unread_notices > 0
            %span.unread-alart
              = fa_icon "exclamation-circle"
        %p.right
          >
    = link_to user_my_page_path('profile') do
      %li{ class: "#{menu_active(@info_patarn, 'profile')}" }
        %p.left
          プロフィール
        %p.right
          >
    = link_to user_my_page_path('like_video') do
      %li{ class: "#{menu_active(@info_patarn, 'like_video')}" }
        %p.left
          お気に入り(動画)
        %p.right
          >
    = link_to user_my_page_path('like_article') do
      %li{ class: "#{menu_active(@info_patarn, 'like_article')}" }
        %p.left
          お気に入り(記事)
        %p.right
          >
    %li
.my-page__menu__list-sp
  %ul
    = link_to user_my_page_path('notice') do
      %li{ class: "#{menu_active(@info_patarn, 'notice')}" }
        %p
          = fa_icon "bell"
          %br          
          お知らせ
          - if @unread_notices > 0
            %span.unread-alart
              = fa_icon "exclamation-circle"
    = link_to user_my_page_path('profile') do
      %li{ class: "#{menu_active(@info_patarn, 'profile')}" }
        %p
          = fa_icon "id-card"
          %br
          プロフィール
    = link_to user_my_page_path('like_video') do
      %li{ class: "#{menu_active(@info_patarn, 'like_video')}" }
        %p
          = fa_icon "heart"
          %br
          お気に入り
          %br
          (動画)
    = link_to user_my_page_path('like_article') do
      %li{ class: "#{menu_active(@info_patarn, 'like_article')}" }
        = fa_icon "heart"
        %br
        %p
          お気に入り
          %br
          (記事)
    %li
    %li

app/views/users/_notification_list.html.haml
.notification
  - @notices.each do |notice|
    .notification__date
      = adjust_created_at(notice.created_at)
    .notification__title
      = notice.title
    .notification__content
      = adjust_brank_text(notice.message)

app/views/users/_pay-history.html.haml
.payment__box
  .payment__box__date
    2018/10/30
  .payment__box__detail
    %table
      %tr
        %td
          小計
        %td
          ¥1000
      %tr
        %td
          税額
        %td
          ¥80
      %tr
        %td
          合計
        %td
          ¥1080

app/views/users/_pay-info.html.haml
- if @info_patarn == 'pay_info' && current_user.payment.present?
  - if check_pay_regi_status == 3
    .pay-alert
      %p
        ご登録のクレジットカードが無効になっているため
        %br
        プレミアムプランをご利用いただけません。
        %br
        決済カードを変更してください。
  .basic-info
    支払い方法
  .user-info
    クレジットカード
  .basic-info
    ご登録のクレジットカード
  .user-info
    = image_tag "#{@card_brand}.png",size: "40x25"
  .basic-info
    カード下４桁
  .user-info
    = @last4
  .basic-info
    有効期限
  .user-info
    = "#{@exp_year}/#{@exp_month}"

  - if check_pay_regi_status == 2 || check_pay_regi_status == 3
    .basic-info
      ご利用プラン
    .user-info
      メルマガ有料会員プラン(¥300/月,税別)
    .basic-info
      次回決済日
    .user-info
      = "#{adjust_expires_at(@expires_at)}"
  %hr.gray-line
  - if check_pay_regi_status == 2 || check_pay_regi_status == 3
    .pay-btn
      = link_to "メルマガ有料会員プランを解約する", delete_payment_path, class: "pay-btn__delete"

  - if check_pay_regi_status == 1 && @magazine_address_check # クレジットカード登録済み&宛先登録済み：最終確認画面にリンク 
    .pay-btn
      %p
        メルマガ有料会員をご希望の方はこちら
      = link_to "メルマガ有料会員に登録する", new_card_registration_path('subscription'), class: "pay-btn__registration"
    = render "/users/account-plan"
  - elsif check_pay_regi_status == 1  # クレジットカード登録済み：宛先登録画面にリンク
    .pay-btn
      %p
        メルマガ有料会員をご希望の方はこちら
      = link_to "メルマガ有料会員に登録する", new_magazine_path, class: "pay-btn__registration"
    = render "/users/account-plan"
  - elsif @magazine_address_check && check_pay_regi_status != 2  # 宛先登録済み：クレジットカード登録画面にリンク
    .pay-btn
      %p
        メルマガ有料会員をご希望の方はこちら
      = link_to "メルマガ有料会員に登録する", new_card_registration_path('subscription'), class: "pay-btn__registration"
    = render "/users/account-plan"
- else
  .pay-btn
    %p
    = link_to "クレジットカードを登録する", new_card_registration_path('charge'), class: "pay-btn__registration"
  .pay-btn
    %hr.gray-line
    %p
      クレジットカード登録と同時に
      %br
      メルマガ有料会員をご希望の方はこちら
    - if @magazine_address_check
      = link_to "メルマガ有料会員に登録する", new_card_registration_path('subscription'), class: "pay-btn__registration"
    - else
      = link_to "メルマガ有料会員に登録する", new_magazine_path, class: "pay-btn__registration"
  = render "/users/account-plan"

app/views/users/_user-profile.html.haml
%table
  .basic-info
    勤務先
  .user-info
    = current_user.userProfile.work_place
  .basic-info
    職種
  .user-info
    = current_user.userProfile.job
  .basic-info
    専門分野
  .user-info
    = current_user.userProfile.specialized_field
  .basic-info
    勤務先の所在地
  .user-info
    = current_user.userProfile.location
  .basic-info
    性別
  .user-info
    = current_user.userProfile.sex
  .basic-info
    生年月日
  .user-info
    = current_user.userProfile.birthday
  .basic-info
    メールアドレス
  .user-info
    = current_user.email
  .basic-info
    アカウント認証
  .user-info
    = @account_aouth

app/views/users/index.html.haml
- set_meta_tags title: "アカウント登録 【COOK LAB. クックラボ 】プロの料理人向けレシピ動画"
.a-create
  .a-create__title
    = fa_icon "user"
    メルマガ会員登録
  .a-create__select
    .a-create__select__box
      = link_to new_user_registration_customize_path('mail') do
        .mail_aouth.aouth-btn
          = fa_icon "envelope"
          = 'メールアドレスで登録'
      = link_to user_facebook_omniauth_authorize_path do
        .fb_aouth.aouth-btn
          = fa_icon "facebook-f"
          = 'Facebookで登録'
      = link_to user_twitter_omniauth_authorize_path do
        .tw_aouth.aouth-btn
          = fa_icon "twitter"
          = 'Twitterで登録'
      / %p
      /   ※プレミアムアカウントおよび有料コンテンツのご利用をご希望の場合はアカウント登録後に支払情報の登録が必要です。
    .a-create__select__box
      .a-create__select__box__plan
        = render 'account-plan'
        / %p
        /   ※表示価格は税抜

app/views/users/my_page.html.haml
- set_meta_tags noindex: true
.my-page
  .my-page__title
    = fa_icon "user"
    マイページ
  .my-page__menu
    = render 'my-page_menu'
  .my-page__content
    - if @info_patarn == 'notice'
      .my-page__content__box
        .my-page__content__box__title
          = fa_icon "bell"
          COOK LABからのお知らせ
        .my-page__content__box__detail
          = render 'notification_list'
    - elsif @info_patarn == 'profile'
      .my-page__content__box
        .my-page__content__box__title
          = image_tag "profile_icon.png",size: "20x20"
          ="#{current_user.name}さんのプロフィール"
        .my-page__content__box__detail
          = render 'user-profile'
          = link_to edit_user_registration_customize_path(@account_patarn), class: "edit-btn" do
            ▶︎アカウント情報を編集する
        
    - elsif @info_patarn == 'pay_video'
      .my-page__content__box
        .my-page__content__box__title
          = fa_icon "unlock-alt"
          購入した動画
        .my-page__content__box__detail
          = render 'video/search-list'
    - elsif @info_patarn == 'like_video'
      .my-page__content__box
        .my-page__content__box__title
          = fa_icon "heart"
          お気に入り（動画）
        .my-page__content__box__detail
          = render 'video/search-list'
    - elsif @info_patarn == 'like_article'
      .my-page__content__box
        .my-page__content__box__title
          = fa_icon "heart"
          お気に入り（記事）
        .my-page__content__box__detail
          = render 'article/article_search_list'
    - elsif @info_patarn == 'pay_info'
      .my-page__content__box
        .my-page__content__box__title
          = fa_icon "credit-card"
          支払情報
        .my-page__content__box__detail
          = render 'pay-info'
          - if check_pay_regi_status != 0
            = link_to edit_payment_path(current_user.id), class: "edit-btn" do
              ▶︎決済カードを変更する