config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_up/:account_patarn' => 'users/registrations#new', as: :new_user_registration_customize
    get '/users/edit/:account_patarn' => 'users/registrations#edit', as: :edit_user_registration_customize
    get '/users/complete/:sign_in_count' => 'users/registrations#complete', as: :new_user_registration_complete
    get '/users/send/:sign_in_count' => 'users/registrations#mail_send', as: :new_user_registration_send
    get '/users/delete' => 'users/registrations#delete', as: :delete_user
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :top, only: :index
  resources :users, only: [:index]
  get 'users/my_page/:info_patarn' => "users#my_page", as: :user_my_page
  resources :video, only: :show do
    collection do
      # get 'genre_search'
      get 'chef_search'
      get 'search'
      get 'make_suggest'
    end
  end

  get 'video/chef_search_video/:chef_id' => "video#chef_search_video"
  resources :article, only: [:index, :show] do
    collection do
      get 'genre_search'
      get 'search'
    end
  end

  resources :payments, only: [:edit, :create, :destroy] do
    collection do
      post 'purchase_charge'
      post 'purchase_subscription'
      post 'card_change'
    end
  end
  get 'payments/new_card/:pay_patarn' => "payments#new_card", as: :new_card_registration
  get 'payments/delete' => "payments#delete", as: :delete_payment

  post   '/video_like/:video_id' => 'video_likes#create', as: 'video_like_create'
  delete '/video_like/:video_id' => 'video_likes#destroy', as: 'video_like_destroy'
  post   '/article_like/:article_id' => 'article_likes#create', as: 'article_like_create'
  delete '/article_like/:article_id' => 'article_likes#destroy', as: 'article_like_destroy'

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
    end
  end

  resources :magazine, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      post 'confirm'
    end
  end

  root 'top#index'

  get '/sitemap' => 'sitemaps#index' 
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user, inverse_of: :userProfile, optional: true

  def self.registration_card_data(customer, current_user)
    payment = Payment.new
    payment.customer_id = customer.id
    payment.user_id = current_user.id
    payment.save!
  end

  def self.set_subscription_data(subscription_data, plan_id, customer, user)
    if user.payment.present?
      payment = user.payment
      payment.subscription_id = subscription_data.id
      payment.plan_id = plan_id
      payment.expires_at = Time.zone.at(subscription_data.current_period_end)
    else
      payment = Payment.new
      payment.subscription_id = subscription_data.id
      payment.plan_id = plan_id
      payment.expires_at = Time.zone.at(subscription_data.current_period_end)
      payment.customer_id = customer.id
      payment.user_id = user.id
    end
    payment.save!
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :configure_payjp_token, only: [:create, :purchase_subscription, :card_change]
  before_action :card_registration_restrict_check, only: [:new_card, :edit]

  def new_card
    if current_user.pay_regi_status_before_type_cast == 1
      # クレジットカードの登録が完了済みの場合はメルマガ有料会員登録の最終確認画面を表示
      @confirm_patarn = 'magazine_and_credit_finish'
      render 'payments/confirm'
    elsif current_user.pay_regi_status_before_type_cast == 0
      @pay_patarn = params['pay_patarn']
    end
  end

  def create
    payjp_token = configure_payjp_token['payjp-token']
    customer = MyPayjp.get_customer_id(payjp_token, current_user)
    card_registration_restrict_status_record = CardRegistrationRestrict.find_by(user_id: current_user.id)
    @lock_check = card_registration_restrict_status_record.error_count if card_registration_restrict_status_record.present?
    if customer[:error].nil? && @lock_check != 5 && current_user.pay_regi_status_before_type_cast == 0
      Payment.registration_card_data(customer, current_user)
      User.update_pay_regi_status(current_user, 'charge')
      MyPayjp.registration_customer_email(customer, current_user.email)
      @registration_patarn = 'create'
      card_registration_restrict_reset(card_registration_restrict_status_record, 'reset') if card_registration_restrict_status_record.present?
      render 'complete'
    else
      card_registration_restrict_count_add(card_registration_restrict_status_record)
      @pay_patarn = params['pay_patarn']
      render 'new_card'
    end
  end

  def purchase_charge
    charge_check = Charge.where(user_id: current_user.id, video_id: params[:video_id])
    if charge_check.empty?
      customer = MyPayjp.get_customer_id('', current_user)
      charge_data = MyPayjp.production_charge(params[:price], customer)
      @result = charge_error_check(charge_data, params[:video_id])
    else
      @result = ['error']
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  def purchase_subscription
    access_type = params[:access_type]
    payjp_token = configure_payjp_token['payjp-token']
    customer = MyPayjp.get_customer_id(payjp_token, current_user)
    card_registration_restrict_status_record = CardRegistrationRestrict.find_by(user_id: current_user.id)
    @lock_check = card_registration_restrict_status_record.error_count if card_registration_restrict_status_record.present?
    plan_id = "mmm_premium_10per"
    subscription_data = MyPayjp.create_subscription(customer, plan_id) if customer[:error].nil?
    if customer[:error].nil? && subscription_data[:error].nil? && @lock_check != 5 && current_user.pay_regi_status_before_type_cast != 2
      MyPayjp.registration_customer_email(customer, current_user.email)
      Payment.set_subscription_data(subscription_data, plan_id, customer, current_user)
      User.update_pay_regi_status(current_user, 'subscription')
      card_registration_restrict_reset(card_registration_restrict_status_record, 'reset') if card_registration_restrict_status_record.present?
      @registration_patarn = 'create'
      render 'complete'
    else
      if access_type == 'direct'
        # 登録済みのカードにエラーがある場合はカード登録画面に移動し新しいカードの入力を促す
        flash[:alert] = '通信エラーが発生しました。' if customer[:error].present? && subscription_data[:error].nil?
        flash[:alert] = 'ご登録されているクレジットカードでの登録が出来ませんでした。' if subscription_data[:error].present?
        @confirm_patarn = 'magazine_and_credit_finish'
        render 'payments/confirm'
      elsif access_type == 'new_card'
        # card_registration_restrict_count_add(card_registration_restrict_status_record)
        flash[:alert] = 'ご登録されているクレジットカードでの登録が出来ませんでした。'
        @pay_patarn = params['pay_patarn']
        render 'new_card'
      end
    end
  end

  def destroy
    result = MyPayjp.delete_subscription_data(current_user.payment.subscription_id)
    if result[:error].nil?
      User.delete_user_subscription_data(current_user)
      #お届け先住所を削除
      MagazineAddress.delete_address(current_user)
      #お気に入り登録を全て削除
      VideoLike.where(user_id: current_user.id).delete_all
      ArticleLike.where(user_id: current_user.id).delete_all
      @registration_patarn = 'delete'
      render 'complete'
    else
      flash.now[:alert] = 'メルマガ有料会員の解約手続きに失敗しました。お手数ですが再度ボタンを押下ください。'
      render 'delete'
    end
  end

  def card_change
    payjp_token = configure_payjp_token['payjp-token']
    customer = MyPayjp.get_customer_id(payjp_token, current_user)
    default_card_id = customer.default_card
    card_registration_restrict_status_record = CardRegistrationRestrict.find_by(user_id: current_user.id)
    @lock_check = card_registration_restrict_status_record.error_count if card_registration_restrict_status_record.present?
    result = MyPayjp.cards_add(customer, payjp_token)
    if result[:error].nil? && @lock_check != 5
      MyPayjp.cards_delete(customer, default_card_id)
      card_registration_restrict_reset(card_registration_restrict_status_record, 'reset') if card_registration_restrict_status_record.present?
      resume_subscription if current_user.pay_regi_status_before_type_cast == 3
      @registration_patarn = 'change'
      render 'complete'
    else
      card_registration_restrict_count_add(card_registration_restrict_status_record)
      render 'edit'
    end
  end

  private

  def charge_error_check(charge_data, video_id)
    @result = if charge_data[:error].present?
                flash[:alert] = 'ご登録されているクレジットカードでの支払いが出来ませんでした。'
                ['error']
              else
                Charge.create(user_id: current_user.id, video_id: video_id, price: charge_data['amount'], payjp_charge_id: charge_data['id'])
                flash[:notice] = '支払が完了しました。'
                ['ok']
              end
  end

  def configure_payjp_token
    if params['payjp-token'].nil?
      '-'
    else
      params.permit('payjp-token')
    end
  end

  def card_registration_restrict_check
    card_registration_restrict_status_record = CardRegistrationRestrict.find_by(user_id: current_user.id)
    card_registration_eternal_restrict_check(card_registration_restrict_status_record)
    if card_registration_restrict_status_record.nil? || (card_registration_restrict_status_record.present? && card_registration_restrict_status_record.error_count < 5)
      @card_registration_restrict_check = nil
    elsif (Time.current - card_registration_restrict_status_record.locked_at).to_i > 3_600
      card_registration_restrict_reset(card_registration_restrict_status_record, 'time_reset')
      @card_registration_restrict_check = nil
    else
      @card_registration_restrict_check = 'lock'
    end
  end

  def card_registration_eternal_restrict_check(card_registration_restrict_status_record)
    @card_registration_eternal_restrict_check = 'lock' if card_registration_restrict_status_record.present? && card_registration_restrict_status_record.total_error_count > 19
  end

  def card_registration_restrict_reset(card_registration_restrict_status_record, reset_type)
    card_registration_restrict_status_record.update(error_count: 0, locked_at: nil, total_error_count: 0) if reset_type == 'reset'
    card_registration_restrict_status_record.update(error_count: 0, locked_at: nil) if reset_type == 'time_reset'
  end

  def card_registration_restrict_count_add(card_registration_restrict_status_record)
    flash.now[:alert] = if card_registration_restrict_status_record.nil?
                          CardRegistrationRestrict.create(user_id: current_user.id, error_count: 1)
                          'クレジットカードの登録処理に失敗しました。お手数ですが再度カード情報をご登録ください。'
                        elsif (new_error_count = card_registration_restrict_status_record.error_count + 1) < 5
                          new_total_error_count = card_registration_restrict_status_record.total_error_count + 1
                          card_registration_restrict_status_record.update(error_count: new_error_count, total_error_count: new_total_error_count)
                          'クレジットカードの登録処理に失敗しました。お手数ですが再度カード情報をご登録ください。'
                        elsif new_error_count > 5
                          @card_registration_restrict_check = 'lock'
                          '無効な操作です！'
                        elsif (new_total_error_count = card_registration_restrict_status_record.total_error_count + 1) < 20
                          card_registration_restrict_status_record.update(error_count: new_error_count, locked_at: Time.now.to_i, total_error_count: new_total_error_count)
                          @card_registration_restrict_check = 'lock'
                          'クレジットカードの登録処理に5回連続失敗しました。お手数ですが１時間後に再度カード情報をご登録ください。'
                        else
                          card_registration_restrict_status_record.update(error_count: new_error_count, locked_at: Time.now.to_i, total_error_count: new_total_error_count)
                          @card_registration_restrict_check = 'lock'
                          @card_registration_eternal_restrict_check = 'lock'
                          'クレジットカードの登録処理に20回連続失敗したため、ロックがかかりました。'
                        end
  end

  def resume_subscription
    User.update_pay_regi_status(current_user, 'subscription')
    MyPayjp.resume_subscription(current_user.payment.subscription_id)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_card-form.html.haml
.payjp__form
  .payjp__form__title
    支払情報
  .payjp__form__brand
    = image_tag('card_visa.png')
    = image_tag('card_mastercard.png')
    = image_tag('card_jcb.png')
    = image_tag('card_amex.png')
    = image_tag('card_dinersclub.png')
    = image_tag('card_discover.png')
    = telephone_field_tag "dummy-cc-number", nil, style: "top: -100px; left: -100px; position: fixed;"
  .payjp__form__form-group
    %label{ for: "card_number", class: "col-sm-2 control-label" }
      カード番号
    .col-sm
      = telephone_field_tag "cc-number", nil, class: "form-control cc-number alphabet", id: "cc-number", placeholder: "1234 5678 9012 3456", "x-autocompletetype" => "cc_number", "data-numeric" => "true", autocomplete: 'off', required: true
  .payjp__form__form-group
    %label{ for: "cc-csc" }
      CVC番号
    .col-sm
      = telephone_field_tag "cc-csc", nil, class: "form-control cc-csc", id: "cc-csc", placeholder: "CVC", required: true
  .payjp__form__form-group
    %label{ for: "cc-exp", class: "col-sm-2 control-label" }
      有効期限
    .col-sm
      = telephone_field_tag "cc-exp", nil, class: "form-control cc-exp alphabet", id: "cc-exp", "data-numeric" => "true", "x-autocompletetype" => "cc-exp", placeholder: "MM/YY", required: true, maxlength: "7"
  .payjp__form__form-group
    %label{ for: "cc_holder", class: "col-sm-2 control-label" }
      カード名義
    .col-sm
      = text_field_tag "cc-holder", nil, class: "form-control cc-holder alphabet", id: "cc-holder", placeholder: "TARO YAMADA", "x-autocompletetype" => "cc-full-name", required: true, pattern: "[A-Z]+\s[A-Z]+"
  = hidden_field_tag :public_key, "#{Settings.payjp[:PAYJP_PUBLIC_KEY]}", id: "public_key"
  = hidden_field_tag "payjp-token", "", id: "payjp-token"
  = hidden_field_tag "pay_patarn", "#{@pay_patarn}"

app/views/payments/complete.html.haml
- set_meta_tags noindex: true
.pay-frame
  .pay-frame__complete
    - if check_pay_regi_status == 1 && @registration_patarn == 'create'
      .pay-frame__complete__title
        %p
          クレジットカードの登録が
        %p
          完了しました
      .pay-frame__complete__btn
        = link_to "戻る", session[:previous_url]
    - elsif check_pay_regi_status != 0 && @registration_patarn == 'change'
      .pay-frame__complete__title
        %p
          クレジットカードの変更手続きが
        %p
          完了しました
      .pay-frame__complete__btn
        = link_to "戻る", session[:previous_url]
    - elsif check_pay_regi_status == 2 && @registration_patarn == 'create'
      .pay-frame__complete__title
        %p
          メルマガ有料会員の登録手続きが
        %p
          完了しました！
      .pay-frame__complete__magazine
        %p
          今後ご登録の住所に
        %br
        = image_tag "cooklab_magazine_logo.jpg", alt: "cooklab_magazine"
        %br
        = image_tag "cooklab_magazine.jpg", alt: "cooklab_magazine", class: "magazine_img"
        %br
        %br
        %p
          を隔月でお届け致します。
        %br
        %p
          引き続き
          %br
          当サイトのコンテンツもお楽しみください。
      .pay-frame__complete__btn
        = link_to "COOK LAB. トップへ", root_path
    - elsif check_pay_regi_status < 2 && @registration_patarn == 'delete'
      .pay-frame__complete__title
        %p
        メルマガ有料会員の解約手続きが
        %p
        完了しました
      .pay-frame__complete__btn
        = link_to "COOK LAB トップへ", root_path

app/views/payments/confirm.html.haml
- if @confirm_patarn == 'magazine_and_credit_finish'
  .pay-frame
    .pay-frame__confirm
      .pay-frame__confirm__route
        %p.now
          メルマガ有料会員 登録確認
        %p
          >>
        %p
          登録完了
      .pay-btn
        %p
          下記のボタンをクリック後に
          %br
          メルマガ有料会員の登録が完了します。
        = link_to purchase_subscription_payments_path(params: { access_type: "direct" }), method: :post, class: "pay-btn__confirm" do
          = "月額300円(税抜)の"
          %br
          = "メルマガ有料会員に登録"

app/views/payments/delete.html.haml
- set_meta_tags noindex: true
.pay-frame
  - if check_pay_regi_status == 2 || check_pay_regi_status == 3
    .pay-frame__title
      プラン解約
    .pay-frame__select
      .delete-frame
        %p
          下記項目をご確認の上、
          %br/
          "解約"ボタンをクリックしてください。
        .delete-frame__alert
          %ul
            %li
              解約後はご指定の住所への COOK LAB magazine のお届けは
              致しませんのでご了承ください。
            %li
              お気に入りに登録された記事・動画は全てリセットされます。
        .delete-frame__checkbox
          %table
            %tr
              %td
                = check_box_tag :concent, id: 'check'
              %td
                = label_tag :concent, "上記項目を理解した上でアカウントを削除します。"
        .delete-frame__actions
          = link_to "/payments/#{current_user.payment.id}", method: :delete, class: 'delete-btn able' do
            = "メルマガ有料会員プラン(¥300/月)を解約する"
        .delete-frame__actions
          %p.delete-btn.disable
            = "メルマガ有料会員プラン(¥300/月)を解約する"
    .pay-frame__back
      %br
      = link_to "◀︎マイページ", user_my_page_path('pay_info')

app/views/payments/edit.html.haml
- set_meta_tags noindex: true
.pay-frame
  .pay-frame__title
    カード情報の変更
  .pay-frame__select
    - if check_pay_regi_status != 0 && @card_registration_restrict_check != 'lock'
      %p
        %b
          決済カードを変更する方は、
          %br/
          カード情報を入力し
          %br/
          登録ボタンを押下してください。
          %br/
          %span.error_alert
            (※自動入力を利用するとエラーが発生する可能性があります)
      = form_tag(action: :card_change, method: :post, id: "payjp-form") do
        = javascript_include_tag "https://js.pay.jp"
        .payjp
          = render 'card-form'
          %button{ id: "token" }
            登録
    - elsif @card_registration_eternal_restrict_check == 'lock'
      %p
        %b
          20回連続で入力情報にエラーがあったため
          %br/
          ロックがかかっています。
          %br/
          カード情報を登録することは
          %br/
          できません。
          %br/
          詳しくはサイト管理者に
          %br/
          お問い合わせください。
    - elsif @card_registration_restrict_check == 'lock'
      %p
        %b
          現在ロックがかかっているため
          %br/
          カード情報を登録することは
          %br/
          できません。
          %br/
          １時間後に再度アクセスしてください。
  .pay-frame__back
    = link_to "◀︎戻る", user_my_page_path('pay_info')

app/views/payments/new_card.html.haml
- set_meta_tags noindex: true
.pay-frame
  .pay-frame__title
    支払情報の登録/編集
  .pay-frame__select
    - if @pay_patarn == 'charge' && current_user.payment.nil? && @card_registration_restrict_check != 'lock'
      %p
        カード情報を入力し
        %br/
        登録ボタンを押下してください。
        %br/
        %span.error_alert
          (※自動入力を利用するとエラーが発生する可能性があります)
      = form_tag(controller: :payments, action: :create, method: :post) do
        = javascript_include_tag "https://js.pay.jp"
        .payjp
          = render 'card-form'
          %button{ id: "token" }
            登録
    - elsif @card_registration_eternal_restrict_check == 'lock'
      %p
        %b
          20回連続で入力情報にエラーがあったため
          %br/
          ロックがかかっています。
          %br/
          カード情報を登録することは
          %br/
          できません。
          %br/
          詳しくはサイト管理者に
          %br/
          お問い合わせください。
    - elsif @card_registration_restrict_check == 'lock'
      %p
        %b
          現在ロックがかかっているため
          %br/
          カード情報を登録することは
          %br/
          できません。
          %br/
          １時間後に再度アクセスしてください。
    - elsif @pay_patarn == 'subscription' && check_pay_regi_status == 0
      %p
        カード情報を入力し
        %br/
        登録ボタンを押下してください。
        %br/
        %span.error_alert
          (※自動入力を利用するとエラーが発生する可能性があります)
      = form_tag(controller: :payments, action: :purchase_subscription, method: :post) do
        = javascript_include_tag "https://js.pay.jp"
        .payjp
          = render 'payments/card-form'
          = hidden_field_tag :access_type, "new_card"
          %button{ id: "token" }
            登録
  .pay-frame__back
    = link_to "◀︎マイページ", user_my_page_path('pay_info')