config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_up/:account_patarn' => 'users/registrations#new', as: :new_user_registration_customize
    get '/users/edit/:account_patarn' => 'users/registrations#edit', as: :edit_user_registration_customize
    get '/users/complete/:sign_in_count' => 'users/registrations#complete', as: :new_user_registration_complete
    get '/users/send/:sign_in_count' => 'users/registrations#mail_send', as: :new_user_registration_send
    get '/users/delete' => 'users/registrations#delete', as: :delete_user
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :top, only: :index
  resources :users, only: [:index]
  get 'users/my_page/:info_patarn' => "users#my_page", as: :user_my_page
  resources :video, only: :show do
    collection do
      # get 'genre_search'
      get 'chef_search'
      get 'search'
      get 'make_suggest'
    end
  end

  get 'video/chef_search_video/:chef_id' => "video#chef_search_video"
  resources :article, only: [:index, :show] do
    collection do
      get 'genre_search'
      get 'search'
    end
  end

  resources :payments, only: [:edit, :create, :destroy] do
    collection do
      post 'purchase_charge'
      post 'purchase_subscription'
      post 'card_change'
    end
  end
  get 'payments/new_card/:pay_patarn' => "payments#new_card", as: :new_card_registration
  get 'payments/delete' => "payments#delete", as: :delete_payment

  post   '/video_like/:video_id' => 'video_likes#create', as: 'video_like_create'
  delete '/video_like/:video_id' => 'video_likes#destroy', as: 'video_like_destroy'
  post   '/article_like/:article_id' => 'article_likes#create', as: 'article_like_create'
  delete '/article_like/:article_id' => 'article_likes#destroy', as: 'article_like_destroy'

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
    end
  end

  resources :magazine, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      post 'confirm'
    end
  end

  root 'top#index'

  get '/sitemap' => 'sitemaps#index' 
end

app/controllers/magazine_controller.rb
class MagazineController < ApplicationController
  before_action :magazine_address_confirm_params, only: [:confirm]
  before_action :magazine_address_update_confirm_params, only: [:confirm]
  before_action :magazine_address_create_params, only: [:create]

  def new
    @magazine_address = MagazineAddress.new
    @crud_patarn = 'create'
  end

  def confirm
    @crud_patarn = params[:crud_patarn]
    if @crud_patarn == 'create'
      @magazine_address = MagazineAddress.new(magazine_address_confirm_params)
      return if @magazine_address.valid?
      render :new
    elsif @crud_patarn == 'update'
      @magazine_address = MagazineAddress.new(magazine_address_update_confirm_params)
      return if @magazine_address.valid?
      render :edit
    end
  end

  def create
    MagazineAddress.create(magazine_address_create_params.merge(user_id: current_user.id)) unless MagazineAddress.find_by(user_id: current_user.id)
    if current_user.pay_regi_status_before_type_cast == 0
      @pay_patarn = 'subscription'
      redirect_to new_card_registration_path('subscription') # renderでなくredirectしないとpayjp tokenの発行ができない
    elsif current_user.pay_regi_status_before_type_cast == 1
      # クレジットカードの登録が完了済みの場合はメルマガ有料会員登録の最終確認画面を表示
      @confirm_patarn = 'magazine_and_credit_finish'
      render 'payments/confirm'
    end
  end

  def edit
    @magazine_address = MagazineAddress.find_by(user_id: current_user.id)
    @crud_patarn = 'update'
  end

  def update
    MagazineAddress.update(magazine_address_create_params.merge(user_id: current_user.id))
    render 'complete'
  end

  private

  def magazine_address_confirm_params
    params.require(:magazine_address).permit(:address, :zipcode, :building).merge(pref: params[:pref], city_address: params[:city_address])
  end

  def magazine_address_update_confirm_params
    params.require(:magazine_address).permit(:address, :zipcode, :building).merge(pref: params[:pref], city_address: params[:city_address], id: params[:id])
  end

  def magazine_address_create_params
    params.require(:magazine_address).permit(:address, :zipcode, :pref, :city_address, :building)
  end
end

app/helpers/magazine_helper.rb
module MagazineHelper
  def set_crud_path(crud_patarn)
    if crud_patarn == 'create'
      magazine_index_path
    else
      magazine_path(@magazine_address.id)
    end
  end

  def set_crud_method(crud_patarn)
    if crud_patarn == 'create'
      'POST'
    else
      'PATCH'
    end
  end
end

app/views/magazine/_magazine-form.html.haml
.a-create__form
  = form_for @magazine_address, url: confirm_magazine_index_path, method: :post do |f|
    .a-create__form__text
      下記項目を入力してください。
      %br
      %p.sup_explanation
        ※郵便番号を入力すると自動的に住所が入力されます。番地等を追加でご記入ください。
      .a-create__form__error
        .message
          - @magazine_address.errors.full_messages.each do |message|
            = message              
      .a-create__form__magazine-box
        .field
          %label
            宛先名
          %br
          = f.text_field :address, class: "s-window", autocomplete: 'off', required: true
        .field
          %label
            郵便番号
          %p.sup_explanation
            ※半角数字で入力してください。"-"は必要ありません。
          %br
          = f.text_field :zipcode, class: "zipcode-window", autocomplete: 'off', maxlength: 7, onKeyUp: "AjaxZip3.zip2addr(this,'','pref','city_address');", required: true
        .field
          %label
            都道府県
          %br
          = f.text_field :pref, class: "s-window", autocomplete: 'off', name: "pref", required: true
        .field
          %label
            市区町村番地
          %br
          = f.text_field :city_address, class: "s-window", autocomplete: 'off', name: "city_address", required: true
        .field
          %label
            マンション名/建物名
          %br
          = f.text_field :building, class: "s-window", autocomplete: 'off'
    .a-create__form__actions
      = hidden_field_tag :crud_patarn, @crud_patarn
      = hidden_field_tag :id, @magazine_address.id
      = button_tag "登録",class: "submit__btn magazine-form-btn"

app/views/magazine/complete.html.haml
.a-create
  .a-create__title
    お届け先住所の変更
  .a-create__complete-main
    お届け先の変更が完了しました。
    .a-create__complete-main__btn
      = link_to "マイページへ", user_my_page_path('profile')

app/views/magazine/confirm.html.haml
.a-create
  - if @crud_patarn == 'create'
    .a-create__title
      メルマガ有料会員登録
    .a-create__route
      %p.now
        お届け先住所登録
      %p
        >>
      %p
        クレジットカード情報登録
      %p
        >>
      %p
        登録完了
  - elsif @crud_patarn == 'update'
    .a-create__title
      お届け先の変更
  .a-create__form
    = form_for @magazine_address, url: set_crud_path(@crud_patarn), method: set_crud_method(@crud_patarn) do |f|
      .a-create__form__text
        下記の内容でお間違えないですか？
        %br
        .a-create__form__magazine-box.confirm-box
          .field
            %u
              宛先名
            %p.input_confirm
              = @magazine_address.address
            = f.hidden_field :address
          .field
            %u
              郵便番号
            %p.input_confirm
              = "〒#{@magazine_address.zipcode.to_s[0..2]}-#{@magazine_address.zipcode.to_s[3..6]}"
            = f.hidden_field :zipcode
          .field
            %u
              都道府県
            %p.input_confirm
              = @magazine_address.pref
            = f.hidden_field :pref
          .field
            %u
              市区町村番地
            %p.input_confirm
              = @magazine_address.city_address
            = f.hidden_field :city_address
          .field
            %u
              マンション名/建物名
            %p.input_confirm
              = @magazine_address.building
            = f.hidden_field :building
          
      .a-create__form__actions
        = button_tag "登録",class: "submit__btn magazine-form-btn"

app/views/magazine/edit.html.haml
.a-create
  .a-create__title
    お届け先住所の変更
  = render 'magazine-form'     

app/views/magazine/new.html.haml
.a-create
  .a-create__title
    メルマガ有料会員登録
  .a-create__route
    - if check_pay_regi_status == 0
      %p.now
        お届け先住所登録
      %p
        >>
      %p
        クレジットカード情報登録
      %p
        >>
      %p
        登録完了
    - if check_pay_regi_status == 1
      %p.now
        お届け先住所登録
      %p
        >>
      %p
        有料メルマガ会員 登録確認
      %p
        >>
      %p
        登録完了
  = render 'magazine-form'     